apiVersion: v1
kind: Pod
metadata:
  name: go-k8s-srv
  labels:
    app: web
spec:
  containers:
    - name: go-k8s-srv
      image: go-k8s-srv:1.0
      ports:
        - containerPort: 8080
      resources:
        limits:
          memory: 512Mi
          cpu: "1"
        requests:
          memory: 256Mi
          cpu: "0.2"
